# Numpy clip and NaN

In [2]:
import numpy as np

In [3]:
d = np.array([10,20,30,40,50,60,70,80,90,100])

In [4]:
d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
e = np.arange(10)

In [6]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
e = np.arange(10,100)

In [8]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [9]:
e = np.arange(10,101,10)

In [10]:
e

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
d>50

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
d[d>50]

array([ 60,  70,  80,  90, 100])

In [13]:
d[e<50]

array([10, 20, 30, 40])

In [14]:
d[d>100]

array([], dtype=int32)

In [17]:
d.clip(30,70)

array([30, 30, 30, 40, 50, 60, 70, 70, 70, 70])

## NaN - Not a Number

In [18]:
f = np.array([10,20,np.NaN,40,50])

In [19]:
f

array([10., 20., nan, 40., 50.])

In [20]:
np.isnan(f)

array([False, False,  True, False, False])

In [21]:
~np.isnan(f)

array([ True,  True, False,  True,  True])

In [24]:
f[np.isnan(f)]

array([nan])

In [25]:
f[~np.isnan(f)]

array([10., 20., 40., 50.])