## Aryphmetic for arrays

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])

In [3]:
a*2

array([20, 40, 60, 80])

In [4]:
a/20

array([0.5, 1. , 1.5, 2. ])

In [5]:
a**2 #степень

array([ 100,  400,  900, 1600], dtype=int32)

In [6]:
a**2-100

array([   0,  300,  800, 1500], dtype=int32)

In [7]:
a**3 - a**2

array([  900,  7600, 26100, 62400], dtype=int32)

In [8]:
1/a

array([0.1       , 0.05      , 0.03333333, 0.025     ])

In [9]:
(a-200)*a/200

array([ -9.5, -18. , -25.5, -32. ])

In [10]:
a*a

array([ 100,  400,  900, 1600])

In [11]:
a/a

array([1., 1., 1., 1.])