## Numpy array reshape and copy

In [1]:
import numpy as np

In [4]:
a = np.arange(10,21,2)

In [5]:
a

array([10, 12, 14, 16, 18, 20])

In [6]:
a.shape

(6,)

In [7]:
a.reshape([2,3])

array([[10, 12, 14],
       [16, 18, 20]])

In [8]:
b = a.reshape([3,2])

In [9]:
b

array([[10, 12],
       [14, 16],
       [18, 20]])

In [10]:
a

array([10, 12, 14, 16, 18, 20])

In [11]:
a[0]

10

In [12]:
b[0]

array([10, 12])

In [13]:
b[0][0] == a[0]

True

In [14]:
b[0][0] == 0

False

In [15]:
a[0] == 10

True

In [16]:
c = b.copy()

In [17]:
a[0]=0

In [18]:
a

array([ 0, 12, 14, 16, 18, 20])

In [19]:
c

array([[10, 12],
       [14, 16],
       [18, 20]])

In [20]:
c.reshape([1,-1])

array([[10, 12, 14, 16, 18, 20]])

In [21]:
a.reshape([2,-1])

array([[ 0, 12, 14],
       [16, 18, 20]])