## Numpy arrays math

In [1]:
import numpy as np

In [2]:
a = np.arange(2,20,2)

In [3]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [5]:
np.sqrt(a[:2])

array([1.41421356, 2.        ])

In [6]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07])

In [7]:
np.exp(a[2:4])

array([ 403.42879349, 2980.95798704])

In [8]:
np.add(a[2:4],a[4:6])

array([16, 20])

In [9]:
np.maximum(a[2:4],a[4:6])

array([10, 12])

In [10]:
np.minimum(a[2:4],a[4:6])

array([6, 8])

In [12]:
a[:-1].reshape((4,2))

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [13]:
b=a[:-1].reshape((4,2))

In [14]:
b

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [15]:
b.T

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])